
package org.altervista.fabriziocelli.wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestWSService", targetNamespace = "http://fabriziocelli.altervista.org/", wsdlLocation = "http://localhost:8888/testws?wsdl")
public class TestWSService extends Service {

    private final static URL TESTWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.altervista.fabriziocelli.wsClient.TestWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.altervista.fabriziocelli.wsClient.TestWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/testws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/testws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTWSSERVICE_WSDL_LOCATION = url;
    }

    public TestWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWSService() {
        super(TESTWSSERVICE_WSDL_LOCATION, new QName("http://fabriziocelli.altervista.org/", "TestWSService"));
    }

    /**
     * 
     * @return
     *     returns TestWS
     */
    @WebEndpoint(name = "TestWSPort")
    public TestWS getTestWSPort() {
        return super.getPort(new QName("http://fabriziocelli.altervista.org/", "TestWSPort"), TestWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWS
     */
    @WebEndpoint(name = "TestWSPort")
    public TestWS getTestWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fabriziocelli.altervista.org/", "TestWSPort"), TestWS.class, features);
    }

}
